services:
  oracle-database:
    shm_size: 1g
    image: container-registry.oracle.com/database/free:latest
    container_name: "example_database"
    restart: unless-stopped
    ports:
      - "1521:1521"
    volumes:
      - database_volume:/opt/oracle/oradata
    environment:
      - ORACLE_PWD=oracle

  backend:
    container_name: "example_backend"
    image: "example_backend:dev"
    platform: linux/amd64
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/backend

  redis:
    image: redis:6.2.10
    container_name: "example_redis"
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  database_volume:
